// Polish localization for Clerk
// Based on https://clerk.com/docs/customization/localization

export const polishLocalization = {
  locale: "pl",
  socialButtonsBlockButton: "Kontynuuj z {{provider}}",
  dividerText: "lub",
  formFieldLabel__emailAddress: "Adres email",
  formFieldLabel__emailAddresses: "Adresy email",
  formFieldLabel__phoneNumber: "Numer telefonu",
  formFieldLabel__username: "Nazwa użytkownika",
  formFieldLabel__password: "Hasło",
  formFieldLabel__firstName: "Imię",
  formFieldLabel__lastName: "Nazwisko",
  formFieldLabel__backupCode: "Kod zapasowy",
  formFieldLabel__organizationName: "Nazwa organizacji",
  formFieldLabel__organizationSlug: "Adres URL organizacji",
  formFieldLabel__role: "Rola",
  formFieldInputPlaceholder__emailAddress: "adres@email.com",
  formFieldInputPlaceholder__emailAddresses: "adres@email.com, adres2@email.com, ...",
  formFieldInputPlaceholder__phoneNumber: "+48 123 456 789",
  formFieldInputPlaceholder__username: "nazwa_użytkownika",
  formFieldInputPlaceholder__password: "Twoje hasło",
  formFieldInputPlaceholder__firstName: "Jan",
  formFieldInputPlaceholder__lastName: "Kowalski",
  formFieldInputPlaceholder__backupCode: "Wprowadź kod zapasowy",
  formFieldInputPlaceholder__organizationName: "Nazwa Twojej organizacji",
  formFieldInputPlaceholder__organizationSlug: "nazwa-organizacji",
  formFieldError__notEmailAddress: "Nieprawidłowy adres email",
  formFieldError__notValidPassword: "Nieprawidłowe hasło",
  formFieldError__notMatchingPasswords: "Hasła nie są identyczne",
  formFieldError__notPhoneNumber: "Nieprawidłowy numer telefonu",
  formFieldError__invalidCode: "Nieprawidłowy kod",
  formFieldError__backupCodeInvalid: "Nieprawidłowy kod zapasowy",
  formFieldAction__forgotPassword: "Zapomniałeś hasła?",
  formFieldHintText__optional: "Opcjonalnie",
  formButtonPrimary: "Kontynuuj",
  signIn: {
    start: {
      title: "Zaloguj się",
      subtitle: "aby kontynuować do Trello Time Report",
      actionText: "Nie masz konta?",
      actionLink: "Zarejestruj się",
    },
    password: {
      title: "Wprowadź hasło",
      subtitle: "aby zalogować się do {{applicationName}}",
      actionText: "Nie pamiętasz hasła?",
      actionLink: "Zresetuj",
    },
    forgotPassword: {
      title: "Zresetuj hasło",
      subtitle: "Wyślemy Ci link do zresetowania hasła",
      formTitle: "Kod resetowania hasła",
      formSubtitle: "Wprowadź kod resetowania hasła wysłany na Twój adres email",
      resendButton: "Nie otrzymałeś kodu? Wyślij ponownie",
      successMessage: "Link do zresetowania hasła został wysłany na Twój adres email.",
    },
    emailCode: {
      title: "Sprawdź swój email",
      subtitle: "aby kontynuować do {{applicationName}}",
      formTitle: "Kod weryfikacyjny",
      formSubtitle: "Wprowadź kod weryfikacyjny wysłany na Twój adres email",
      resendButton: "Nie otrzymałeś kodu? Wyślij ponownie",
    },
    emailLink: {
      title: "Sprawdź swój email",
      subtitle: "aby kontynuować do {{applicationName}}",
      resendButton: "Nie otrzymałeś linku? Wyślij ponownie",
      unusedTab: {
        title: "Możesz zamknąć tę kartę",
        subtitle: "Kontynuowaliśmy proces logowania w nowej karcie.",
      },
      verified: {
        title: "Zalogowano pomyślnie",
        subtitle: "Zostaniesz przekierowany za chwilę",
      },
      verifiedSwitchTab: {
        title: "Zalogowano pomyślnie",
        subtitle: "Wróć do oryginalnej karty, aby kontynuować",
      },
      loading: {
        title: "Logowanie...",
        subtitle: "Zostaniesz przekierowany za chwilę",
      },
      failed: {
        title: "Link weryfikacyjny jest nieprawidłowy",
        subtitle: "Wróć do oryginalnej karty, aby kontynuować.",
      },
      expired: {
        title: "Link weryfikacyjny wygasł",
        subtitle: "Wróć do oryginalnej karty, aby kontynuować.",
      },
    },
    phoneCode: {
      title: "Sprawdź swój telefon",
      subtitle: "aby kontynuować do {{applicationName}}",
      formTitle: "Kod weryfikacyjny",
      formSubtitle: "Wprowadź kod weryfikacyjny wysłany na Twój numer telefonu",
      resendButton: "Nie otrzymałeś kodu? Wyślij ponownie",
    },
    twoFactor: {
      title: "Weryfikacja dwuetapowa",
      subtitle: "aby kontynuować do {{applicationName}}",
      formTitle: "Kod weryfikacyjny",
      formSubtitle: "Wprowadź kod weryfikacyjny z Twojej aplikacji uwierzytelniającej",
    },
  },
  signUp: {
    start: {
      title: "Utwórz konto",
      subtitle: "aby rozpocząć korzystanie z Trello Time Report",
      actionText: "Masz już konto?",
      actionLink: "Zaloguj się",
    },
    emailLink: {
      title: "Sprawdź swój email",
      subtitle: "aby kontynuować rejestrację",
      resendButton: "Nie otrzymałeś linku? Wyślij ponownie",
      unusedTab: {
        title: "Możesz zamknąć tę kartę",
        subtitle: "Kontynuowaliśmy proces rejestracji w nowej karcie.",
      },
      verified: {
        title: "Zarejestrowano pomyślnie",
        subtitle: "Zostaniesz przekierowany za chwilę",
      },
      verifiedSwitchTab: {
        title: "Zarejestrowano pomyślnie",
        subtitle: "Wróć do oryginalnej karty, aby kontynuować",
      },
      loading: {
        title: "Rejestracja...",
        subtitle: "Zostaniesz przekierowany za chwilę",
      },
      failed: {
        title: "Link weryfikacyjny jest nieprawidłowy",
        subtitle: "Wróć do oryginalnej karty, aby kontynuować.",
      },
      expired: {
        title: "Link weryfikacyjny wygasł",
        subtitle: "Wróć do oryginalnej karty, aby kontynuować.",
      },
    },
    emailCode: {
      title: "Sprawdź swój email",
      subtitle: "aby kontynuować rejestrację",
      formTitle: "Kod weryfikacyjny",
      formSubtitle: "Wprowadź kod weryfikacyjny wysłany na Twój adres email",
      resendButton: "Nie otrzymałeś kodu? Wyślij ponownie",
    },
    phoneCode: {
      title: "Sprawdź swój telefon",
      subtitle: "aby kontynuować rejestrację",
      formTitle: "Kod weryfikacyjny",
      formSubtitle: "Wprowadź kod weryfikacyjny wysłany na Twój numer telefonu",
      resendButton: "Nie otrzymałeś kodu? Wyślij ponownie",
    },
    continue: {
      title: "Uzupełnij brakujące informacje",
      subtitle: "aby kontynuować rejestrację",
    },
  },
  userProfile: {
    title: "Profil użytkownika",
    subtitle: "Zarządzaj swoim profilem użytkownika",
    primaryButton: "Zapisz",
    avatar: {
      title: "Avatar",
      subtitle: "Prześlij lub usuń swój avatar",
      upload: "Prześlij",
      remove: "Usuń",
    },
    name: {
      title: "Imię i nazwisko",
      subtitle: "Ustaw swoje imię i nazwisko",
    },
    email: {
      title: "Adres email",
      subtitle: "Ustaw i zweryfikuj swoje adresy email",
      resendButton: "Wyślij ponownie",
      verificationMessage: "Kod weryfikacyjny został wysłany na Twój adres email.",
    },
    phone: {
      title: "Numer telefonu",
      subtitle: "Ustaw i zweryfikuj swój numer telefonu",
      resendButton: "Wyślij ponownie",
      verificationMessage: "Kod weryfikacyjny został wysłany na Twój numer telefonu.",
    },
    username: {
      title: "Nazwa użytkownika",
      subtitle: "Ustaw swoją nazwę użytkownika",
    },
    password: {
      title: "Hasło",
      subtitle: "Ustaw lub zmień swoje hasło",
      changeButton: "Zmień hasło",
    },
    connectedAccounts: {
      title: "Połączone konta",
      subtitle: "Zarządzaj połączonymi kontami",
      noConnectedAccounts: "Brak połączonych kont",
    },
    mfa: {
      title: "Weryfikacja dwuetapowa",
      subtitle: "Zabezpiecz swoje konto za pomocą weryfikacji dwuetapowej",
      formTitle: "Kod weryfikacyjny",
      formSubtitle: "Wprowadź kod weryfikacyjny z Twojej aplikacji uwierzytelniającej",
      primaryButton: "Włącz",
      verifiedTitle: "Weryfikacja dwuetapowa została włączona",
      verifiedSubtitle: "Twoje konto jest teraz zabezpieczone weryfikacją dwuetapową.",
    },
    danger: {
      title: "Strefa niebezpieczna",
      subtitle: "Usuń swoje konto i wszystkie powiązane dane",
      deleteAccountButton: "Usuń konto",
    },
  },
  organizationProfile: {
    title: "Profil organizacji",
    subtitle: "Zarządzaj profilem organizacji",
    primaryButton: "Zapisz",
    avatar: {
      title: "Avatar",
      subtitle: "Prześlij lub usuń avatar organizacji",
      upload: "Prześlij",
      remove: "Usuń",
    },
    name: {
      title: "Nazwa",
      subtitle: "Ustaw nazwę organizacji",
    },
    slug: {
      title: "Adres URL",
      subtitle: "Ustaw adres URL organizacji",
    },
    members: {
      title: "Członkowie",
      subtitle: "Przeglądaj i zarządzaj członkami organizacji",
      inviteMember: "Zaproś członka",
      removeMember: "Usuń",
    },
    danger: {
      title: "Strefa niebezpieczna",
      subtitle: "Usuń tę organizację i wszystkie powiązane dane",
      deleteOrganizationButton: "Usuń organizację",
    },
  },
  organizationSwitcher: {
    personalWorkspace: "Osobista przestrzeń robocza",
    notSelected: "Nie wybrano organizacji",
    createOrganization: "Utwórz organizację",
  },
  userButton: {
    signOut: "Wyloguj się",
    userProfile: "Profil użytkownika",
    organizationProfile: "Profil organizacji",
    manageOrganization: "Zarządzaj organizacją",
    createOrganization: "Utwórz organizację",
  },
  organizationInvitation: {
    title: "Zaproszenie do organizacji",
    subtitle: "Zostałeś zaproszony do dołączenia do {{organizationName}}",
    acceptInvitation: "Akceptuj zaproszenie",
    declineInvitation: "Odrzuć zaproszenie",
  },
  passwordReset: {
    title: "Zresetuj hasło",
    subtitle: "Ustaw nowe hasło dla swojego konta",
    formTitle: "Nowe hasło",
    formSubtitle: "Wprowadź nowe hasło dla swojego konta",
    submit: "Zresetuj hasło",
  },
  continue: {
    title: "Kontynuuj",
    subtitle: "aby przejść do {{applicationName}}",
  },
  errors: {
    something_went_wrong: "Coś poszło nie tak",
    invalid_request_error: "Nieprawidłowe żądanie",
    invalid_email_error: "Nieprawidłowy adres email",
    invalid_phone_error: "Nieprawidłowy numer telefonu",
    invalid_password_error: "Nieprawidłowe hasło",
    invalid_code_error: "Nieprawidłowy kod",
    invalid_credentials_error: "Nieprawidłowe dane logowania",
    invalid_session_error: "Sesja wygasła. Zaloguj się ponownie.",
    rate_limit_error: "Zbyt wiele prób. Spróbuj ponownie później.",
    unauthorized_error: "Brak uprawnień do wykonania tej akcji",
    not_found_error: "Nie znaleziono",
  },
  dates: {
    seconds: "{{count}} sekund",
    minutes: "{{count}} minut",
    hours: "{{count}} godzin",
    days: "{{count}} dni",
    weeks: "{{count}} tygodni",
    months: "{{count}} miesięcy",
    years: "{{count}} lat",
    now: "teraz",
    ago: "temu",
  },
};
